### ISSUE TITLE
Parse Request URL

### ISSUE THREAD

**Issue by toyseed** [NamsooCho/WebServer_2#7]
url 을 파싱하고 역할을 구분해서 저장할 수 있는 구조체를 생성합니다.

request header 에 포함된 요청 url 을 파싱해서 이후 로직에 유효한 구조체를 생성합니다. 구조체에는 pathname, query, hash 등이 포함되어 라이팅이나 response 생성을 위한 로직에 활용할 예정입니다.

**Comment by NamsooCho** [comment]
이슈의 앞뒤 사정과 이슈 내용에 대하여 다른 사람이 이해하기 쉽게 써 주시면 좋아요

**Comment by toyseed** [comment]
설명 보충했습니다. : )
